CONFIG = dict()
CONFIG["aris.compute"] = 20
CONFIG["aris.compute.big"] = 20
CONFIG["grid5000.grenoble.dahu"] = 16
CONFIG["grid5000.nancy.gros"] = 18
CONFIG["grid5000.rennes.paravance"] = 8
CONFIG["grid5000.nancy.grvingt"] = 16 # check total cores per node
CONFIG["iccs-g5k.nancy.gros"] = 18
CONFIG["iccs-g5k.rennes.paravance"] = 8
CONFIG["iccs-g5k.nancy.grvingt"] = 32 # check total cores per node
CONFIG["iccs-g5k.grenoble.dahu"] = 32 # check total cores per node
CONFIG["leonardo"] = 32
CONFIG["marconi"] = 48
CONFIG["lrz"] = 48
CONFIG["rennes.paravance.oar"] = 8
CONFIG["remake-g5k.nancy.grvingt"] = 32 # check total cores per node
